# RedHat related OSs
- name: create epel.repo
  action: template src=epel.repo dest=/etc/yum.repos.d/epel.repo 
  when: "ansible_os_family == 'RedHat'"

- name: Yum install $item
  action: yum pkg=$item state=installed
  with_items:
    - ganglia-gmond
    - ganglia-gmetad
  when: "ansible_os_family == 'RedHat'"

# Debian related OSs
- name: Apt install $item
  action: apt pkg=$item state=installed
  with_items:
    - ganglia-monitor
    - gmetad
  when: "ansible_os_family == 'Debian'"

- name: configure ganglia-monitor
  action: template src=gmond.conf dest=/etc/ganglia/gmond.conf owner=root group=root
  notify:
      - restart gmond
      - restart ganglia-monitor

- name: start gmond
  action: service name=gmond state=running
  when: "ansible_os_family == 'RedHat'"
  
- name: configure gmetad
  action: template src=gmetad.conf dest=/etc/ganglia/gmetad.conf owner=root group=root
  notify:
      - restart gmetad-dev
      - restart gmetad
  
- name: start gmetad
  action: service name=gmetad state=running
  when: "ansible_os_family == 'RedHat'"
