- include_vars: "{{ ansible_os_family }}.yml"

- include: ganglia.yml is_client=yes ganglia_gmetad={{ ganglia_gmetad }}
  when: "ganglia_type_of_node == 'slave'"

- include: gmetad.yml is_client=no ganglia_gmetad={{ ganglia_gmetad }}
  when: "ganglia_type_of_node == 'master'"

- name: Open port 8649 - {{item}} in the firewall
  command: iptables -I INPUT -p {{item}} --dport 8649:8649 -j ACCEPT
  ignore_errors: yes
  with_items:
  - udp
  - tcp

- name: save iptables
  shell: iptables-save > /etc/sysconfig/iptables
  when: "ansible_os_family == 'RedHat'"
