- include_vars: "{{ ansible_os_family }}.yml"

- name: check file epel.repo
  stat: path=/etc/yum.repos.d/epel.repo
  register: epel_repo
  when: "ansible_os_family == 'RedHat'"

- name: create epel.repo
  action: template src=epel.repo dest=/etc/yum.repos.d/epel.repo 
  when: "ansible_os_family == 'RedHat' and epel_repo.stat.exists == false"

- include: ganglia.yml is_client=yes
  when: "ganglia_type_of_node == 'slave'"

- include: gmetad.yml is_client=no
  when: "ganglia_type_of_node == 'master'"

- name: Open port 8649 - {{item}} in the firewall
  command: iptables -I INPUT -p {{item}} --dport 8649:8649 -j ACCEPT
  ignore_errors: yes
  with_items:
  - udp
  - tcp

- name: save iptables
  shell: iptables-save > /etc/sysconfig/iptables
  when: "ansible_os_family == 'RedHat'"
