- include: ganglia.yml is_client=yes ganglia_gmetad={{ ganglia_gmetad }}
  when: "ganglia_type_of_node == 'slave'"

- include: gmetad.yml is_client=no ganglia_gmetad={{ ganglia_gmetad }}
  when: "ganglia_type_of_node == 'master'"
